### ISSUE TITLE
getFluidGatsbyImage return srcset with images smaller than the width of original image

### ISSUE THREAD

**Issue by hangindev** [sanity-io/gatsby-source-sanity#32]
I have an image asset uploaded which is 1440px x 640px. When I call `getFluidGatsbyImage`with maxWidth set to 1440px, the function returns srcset with images of 360w and 720w and 1440w is missing, which result in low resolution imgae in my gatsby site.

I looked into the source code and I believe it is [this line](https://github.com/sanity-io/gatsby-source-sanity/blob/a58fa9927b37d7476d78837b8fae1cbd69256652/src/images/getGatsbyImageProps.ts#L256) that filters out the width of original image. May I know if it is intended or not?

**Comment by hongaar** [comment]
I've just bumped into the same issue. Probably an easy fix:

```js
.filter(currentWidth => currentWidth <= dimensions.width)
```

Additionally, I'd also like the original width to be part of the srcSet. The reason for this is because depending on the selected `maxWidth` parameter, the srcSet for an image with a width of - say - 780px may only contain 200px and 400px versions of the image (the next breakpoint is 800px but that gets filtered out as the original width is smaller).

However, for _fluid_ use cases, the image might well render with a width > 400px, which would make the original image a better candidate.

I'd be happy to create a PR for this.
