### ISSUE TITLE
resolveReferences for _raw fields has no impact

### ISSUE THREAD

**Issue by intensr** [sanity-io/gatsby-source-sanity#43]
Not sure if duplicate of/related to: 
https://github.com/sanity-io/gatsby-source-sanity/issues/37

Seems like the _rawContent(resolveReferences: { maxDepth: 10 }) has no impact on exposing the specific refs. 

Query on createPages (_rawContent) in gatsby
![image](https://user-images.githubusercontent.com/6901764/66977871-e1340c00-f0a7-11e9-98c6-fcbc307dd2d7.png)

Logging raw query
![image](https://user-images.githubusercontent.com/6901764/66977809-a3cf7e80-f0a7-11e9-98a9-2ee87021e175.png)

Result of log in frontend
![image](https://user-images.githubusercontent.com/6901764/66977741-6834b480-f0a7-11e9-9f60-e0a41dfa142a.png)

**Comment by rexxars** [comment]
Does the references document still exist? I see the reference is set to weak.

**Comment by intensr** [comment]
Hey Espen,
yes I log several items which all are referenced to different documents, but good point.

**Comment by intensr** [comment]
@rexxars is there any news on this?

**Comment by chandlervdw** [comment]
I, too, have this issue, though I don't have any `_weak` attribute within my unique `mark` attribute object.

![image](https://user-images.githubusercontent.com/332278/70738694-404a8180-1ce3-11ea-88b9-d9b1bfa394c5.png)

**Comment by intensr** [comment]
I investigated a bit further.

Lets say you have those two document types (just for testing purposes)
```
export default {
  name: 'page',
  title: 'Page',
  type: 'document',
  fields: [
    {
      name: 'link',
      title: 'Link',
      type: 'reference',
    }
  ]
}
```
and
```
export default {
  name: 'job',
  title: 'Job',
  type: 'document',
  fields: [
    {
      name: 'page',
      title: 'Page',
      type: 'page',
    },
  ],
};
```

The reference of page will work where the reference of jobs wont work so i guess theres a type nesting problem regarding reference types

**Comment by roffelsaurus** [comment]
this does work for documents referenced to from inside blockcontent. I use a catch all depth 10 on all graphql queries on blockcontent. could perhaps your nesting be deeper than 10?

**Comment by intensr** [comment]
roffelsaurus to the rescue !
can you describe closer what you mean with catch all ? 
regarding the deeper than 10 thing, i've set it to 5000 just to try but that had no impact.

**Comment by chandlervdw** [comment]
I am also seeing unresolved references when they are nested

**Comment by roffelsaurus** [comment]
Nothing special, just a suggestion to try deeper maxdepth. If 5000 did not
work there is sonething else with your model compared to mine.

tir. 4. feb. 2020 kl. 20:43 skrev Chandler Van De Water <
notifications@github.com>:

**Comment by chandlervdw** [comment]
For me, it doesn't resolve image references within any `bodyPortableText` blocks

**Comment by roffelsaurus** [comment]
I did more research and an attempt at fixing this today. 

- no references work as expected and gives you a usable portable(despite #37 claiming otherwise)
`
document {
   object {
      _rawPortable
   }
}
`
- top level field portable with refs work
`
document {
      _rawPortable(resolveReferences: {maxDepth: 10})
}
`
- but portable nested in object does not dereference the { _ref } objects
`
document {
   object {
      _rawPortable(resolveReferences: {maxDepth: 10})
   }
}
`
I got annoying error like "_rawTitle: incorrect OutputType: JSON"from graphql-compose when using npm link on gatsby-source-sanity into my gatsby project, so couldn't actually debug this properly, but just using DEBUG=sanity gave a clue that
resolveReferences was called for the object with _ref, but it gave the error message here:
https://github.com/sanity-io/gatsby-source-sanity/blob/c83a418a21f0af283c3e2d1cb0959a1fd6e0b264/src/util/resolveReferences.ts#L50

**Comment by chandlervdw** [comment]
This fixes the unresolved refs issue: https://github.com/sanity-io/gatsby-source-sanity/pull/66
